// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxneZzRelch7DV8tZStCzhLnX5fW-yg0M',
    appId: '1:135301880194:web:f005510a3541eb0d80179b',
    messagingSenderId: '135301880194',
    projectId: 'hnd9-db536',
    authDomain: 'hnd9-db536.firebaseapp.com',
    databaseURL: 'https://hnd9-db536-default-rtdb.firebaseio.com',
    storageBucket: 'hnd9-db536.firebasestorage.app',
    measurementId: 'G-7WN21NB5GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdGlNCxDOk0ee-XYz2HQ7JaahxdOyv9GQ',
    appId: '1:135301880194:android:684a61c9b9fa5fb780179b',
    messagingSenderId: '135301880194',
    projectId: 'hnd9-db536',
    databaseURL: 'https://hnd9-db536-default-rtdb.firebaseio.com',
    storageBucket: 'hnd9-db536.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYPnHuEjctT8mU1eDUJ6qjik_eb2iC12I',
    appId: '1:135301880194:ios:900080db452cb8c480179b',
    messagingSenderId: '135301880194',
    projectId: 'hnd9-db536',
    databaseURL: 'https://hnd9-db536-default-rtdb.firebaseio.com',
    storageBucket: 'hnd9-db536.firebasestorage.app',
    iosBundleId: 'com.iqonic.streamitlaravel',
  );
}
